version: '3'
services:
    db:
        build:
            context: .
            dockerfile: ./mysql/Dockerfile
        environment: 
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        volumes:
            - ../JoinIt/dbSchema:/usr/data
        ports:
            - 3306:3306
    web:
        build:
            context: .
            dockerfile: ./apache/Dockerfile
            args:
                uid: ${UID}
        environment:
            - APACHE_RUN_USER=#${UID}
            - APACHE_RUN_GROUP=#${UID}
        restart: unless-stopped
        volumes: 
            - ../JoinIt:/var/www/html
            - ./apache_log:/var/log/apache2
        ports:
            - 80:80
        depends_on: 
            - db
        links:
            - db
volumes:
    db_data:
    src: