FROM mysql

ENV MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
ENV MYSQL_DATABASE=${MYSQL_DATABASE}


# COPY ../../JoinIt/dbSchema/shop1_211206_修正匯入錯誤.sql /docker-entrypoint-initdb.d/init.sql
EXPOSE 3306
